In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("HousePricePrediction.csv")
df.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [4]:
df_clean = df.dropna()
df_clean

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,7917,Inside,1Fam,5,1999,2000,VinylSd,0.0,953.0,175000.0
1456,1456,20,RL,13175,Inside,1Fam,6,1978,1988,Plywood,163.0,1542.0,210000.0
1457,1457,70,RL,9042,Inside,1Fam,9,1941,2006,CemntBd,0.0,1152.0,266500.0
1458,1458,20,RL,9717,Inside,1Fam,6,1950,1996,MetalSd,1029.0,1078.0,142125.0
1459,1459,20,RL,9937,Inside,1Fam,6,1965,1965,HdBoard,290.0,1256.0,147500.0

In [5]:
df_clean.select_dtypes(include='object').columns

Index(['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st'], dtype='object')

In [6]:
obj_col = ["MSZoning", "LotConfig", "BldgType", "Exterior1st"]
df_clean = pd.get_dummies(df_clean, columns=obj_col, drop_first=True)

In [7]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   1460 non-null   int64
 1   MSSubClass           1460 non-null   int64
 2   LotArea              1460 non-null   int64
 3   OverallCond          1460 non-null   int64
 4   YearBuilt            1460 non-null   int64
 5   YearRemodAdd         1460 non-null   int64
 6   BsmtFinSF2           1460 non-null   float64
 7   TotalBsmtSF          1460 non-null   float64
 8   SalePrice            1460 non-null   float64
 9   MSZoning_FV          1460 non-null   bool
 10  MSZoning_RH          1460 non-null   bool
 11  MSZoning_RL          1460 non-null   bool
 12  MSZoning_RM          1460 non-null   bool
 13  LotConfig_CulDSac    1460 non-null   bool
 14  LotConfig_FR2        1460 non-null   bool
 15  LotConfig_FR3        1460 non-null   bool
 16  LotConfig_Inside     1460 non-null   bool
 17  BldgType_2fmCon      1460 non-null   bool
 18  BldgType_Duplex      1460 non-null   bool
 19  BldgType_Twnhs       1460 non-null   bool
 20  BldgType_TwnhsE      1460 non-null   bool
 21  Exterior1st_AsphShn  1460 non-null   bool
 22  Exterior1st_BrkComm  1460 non-null   bool
 23  Exterior1st_BrkFace  1460 non-null   bool
 24  Exterior1st_CBlock   1460 non-null   bool
 25  Exterior1st_CemntBd  1460 non-null   bool
 26  Exterior1st_HdBoard  1460 non-null   bool
 27  Exterior1st_ImStucc  1460 non-null   bool
 28  Exterior1st_MetalSd  1460 non-null   bool
 29  Exterior1st_Plywood  1460 non-null   bool
 30  Exterior1st_Stone    1460 non-null   bool
 31  Exterior1st_Stucco   1460 non-null   bool
 32  Exterior1st_VinylSd  1460 non-null   bool
 33  Exterior1st_Wd Sdng  1460 non-null   bool
 34  Exterior1st_WdShing  1460 non-null   bool
dtypes: bool(26), float64(3), int64(6)
memory usage: 151.1 KB

In [8]:
X = df_clean.drop(columns=["Id", "SalePrice"])
y = df_clean["SalePrice"]

In [14]:
X = X.astype(float)

In [15]:
# model training
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size= 0.2, random_state = 42
)

In [17]:
reg_model = LinearRegression()

In [18]:
reg_model.fit(X_train, y_train)

LinearRegression()

In [19]:
y_pred = reg_model.predict(X_test)

In [20]:
from sklearn.metrics import r2_score, mean_squared_error

In [21]:
print("r2_score -> ", r2_score(y_test, y_pred))
print("mean_square error -> ", mean_squared_error(y_test, y_pred))

r2_score ->  0.6195131796544797
mean_square error ->  2918458029.5855436

In [22]:
# with standard scaling

from sklearn.preprocessing import StandardScaler

In [23]:
sclaer = StandardScaler()

In [25]:
X_train_scaled = sclaer.fit_transform(X_train)
X_test_scaled = sclaer.transform(X_test)

In [26]:
reg_model.fit(X_train_scaled, y_train)

LinearRegression()

In [30]:
y_pred = reg_model.predict(X_test_scaled)

In [31]:
print("r2 score -> ", r2_score(y_test, y_pred))
print("mean_squared_error -> ", mean_squared_error(y_test, y_pred))

r2 score ->  0.6195131796544886
mean_squared_error ->  2918458029.5854754